title: Page

options:
  template: true
  status: true
  url: true

fields:
  title:
    label: Title
    type:  text

  intro:
    label: Intro
    type:  textarea

  text:
    label: Text
    type:  textarea
